version: '3.7'
services:

  traefik:
    image: traefik:v2.4
    networks:
      - web-dev
    ports:
      # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
      - target: 80
        published: 80
        mode: host
      # Listen on port 443, default for HTTPS
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      # Add Docker as a mounted volume, so that Traefik can read the labels of other services
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./_volumes/traefik/traefik.yml:/traefik.yml:ro
      - ./_volumes/traefik/traefik-certs.yml:/traefik-certs.yml
      - ./_volumes/traefik/certificates/:/certificates

  mariadb:
    image: mariadb:10.5
    hostname: "plantcrm_mariadb"
    networks:
      - web-dev
    environment:
      MYSQL_ROOT_PASSWORD: "AhXe6K4RE98t^ukH"
      MARIADB_DATABASE: "plantcrm"
      MARIADB_USER: "plantcrm"
      MARIADB_PASSWORD: "AhXe6K4RE98t^ukH"
    volumes:
      - ./_volumes/mysql/database_data/:/var/lib/mysql
      - ./_volumes/mysql/conf.d/:/etc/mysql/conf.d
      - ./_volumes/mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - target: 3306
        published: 3306
        mode: host

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    networks:
      - web-dev
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "8090:80"

  php:
    image: serversideup/php:8.1-fpm-nginx
    working_dir: /var/www/html
    networks:
      - web-dev
    volumes:
      - .:/var/www/html/:cached
    environment:
      AUTORUN_ENABLED: false
    depends_on:
      - "mariadb"
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plantcrm.rule=Host(`plantcrm.dev.test`)"
      - "traefik.http.routers.plantcrm.entrypoints=websecure"
      - "traefik.http.routers.plantcrm.tls=true"
      - "traefik.http.services.plantcrm.loadbalancer.server.port=443"
      - "traefik.http.services.plantcrm.loadbalancer.server.scheme=https"

  redis:
    image: redis:6
    hostname: "plantcrm_redis"
    networks:
      - web-dev
    volumes:
      - ./_volumes/redis/data:/data:cached
    depends_on:
      - "mariadb"
      - "php"
    command: "redis-server --appendonly yes --requirepass redispassword"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025

networks:
  web-dev:
